spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bpass
    username: root
    password: H3q1249*^^*

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        format_sql: true
    hibernate:
      ddl-auto: create
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secretKey: "This Data Must Be Managed By Secret NOT HERE THIS IS JUST EXAMPLE"

log:
  serverName: "Rest Api Template"
  level: ERROR
  slack:
    enabled: true
    webHookUrl: "Slack Webhook URL"
    channel: error-report-bot
    userName: "[API]ErrorReportBot"
  database:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE